POST http://localhost:6000/users/register
Content-Type: application/json

{
  "name": "alex",
  "email": "alex@mail.ru",
  "password": "123456",
  "avatar": "1.png",
  "type": "Common"
}
###
POST http://localhost:6000/users/register
Content-Type: application/json

{
  "name": "alex12346",
  "email": "alex12346@mail.ru",
  "password": "12345678",
  "type": "Common"
}

###
POST http://localhost:6000/users/login
Content-Type: application/json

{
  "email": "alex12346@mail.ru",
  "password": "12345678"
}

###
GET http://localhost:6000/users/login
