POST http://localhost:6000/users/register
Content-Type: application/json

{
  "name": "alex",
  "email": "alex@mail.ru",
  "password": "123456",
  "avatar": "1.png",
  "type": "Common"
}
###
POST http://localhost:6000/users/register
Content-Type: application/json

{
  "userId": "alex123",
  "name": "alex123",
  "email": "alex123@mail.ru",
  "password": "123456",
  "avatar": "1.png",
  "type": "Common"
}

###
POST http://localhost:6000/users/login
Content-Type: application/json

{
  "email": "alex123@mail.ru",
  "password": "123456"
}

###
GET http://localhost:6000/users/login
