POST http://localhost:6000/offers/
Content-Type: application/json

{
  "title": "Небольшой дом",
  "description": "Сдается небольшой дом",
  "postedAt": "2024-07-16T19:00:00.000Z",
  "city": "Paris",
  "imagePreview": "preview2.png",
  "photos": [
    "1.png",
    "2.png",
    "3.png",
    "4.png",
    "5.png",
    "6.png"
  ],
  "isPremium": false,
  "isFavourite": false,
  "rating": 5,
  "housingType": "house",
  "bedroomsAmount": 8,
  "capacity": 10,
  "price": 100000,
  "features": [
    "Breakfast",
    "AirConditioning"
  ],
  "host": "659afb6521dd10af07b19fdc",
  "commentsAmount": 0,
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

GET http://localhost:6000/offers/

###
@offerId = 659c245d8c5858f831724f66

GET http://localhost:6000/offers/{{offerId}}

###

PUT http://localhost:6000/offers/{{offerId}}
Content-Type: application/json

{
  "title": "Приличный дом",
  "postedAt": "2024-07-16T19:00:00.000Z"
}

###

DELETE http://localhost:6000/offers/{{offerId}}

###
@city = Paris

GET http://localhost:6000/offers/premium/{{city}}

###

GET http://localhost:6000/offers/favourites
Content-Type: application/json

{
  "host": "659afb6521dd10af07b19fdc"
}

###

POST http://localhost:6000/offers/{{offerId}}/addFavourite

###

DELETE http://localhost:6000/offers/{{offerId}}/deleteFavourite
