@offerId = 659afb6521dd10af07b19fde

POST http://localhost:6000/comments/{{offerId}}/
Content-Type: application/json

{
  "text": "Не понравилось",

  "postDate": "01.01.2025",

  "rating": "3",

  "host": "659afb6521dd10af07b19fe1",

  "offerId": "659afb6521dd10af07b19fde"
}

###

GET http://localhost:6000/comments/{{offerId}}/
